childBlocks: null
field: 92f003df-95a6-496d-8716-1a26cb0daf86 # Neo
fieldLayouts:
  ec781207-a393-4135-9651-2ecb59b06bd6:
    tabs:
      -
        elements:
          -
            fieldUid: 77134bd9-63e6-4d74-91b3-9bf7c58f186c # Textfield
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: content
        sortOrder: 1
group: null
handle: test
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
name: test
sortOrder: 1
topLevel: true
