enableVersioning: true
handle: pages
name: Pages
previewTargets:
  -
    label: 'Primary entry page'
    urlFormat: '{url}'
propagationMethod: all
siteSettings:
  62e7f631-6c81-4988-8a6f-3bd46b36321a:
    enabledByDefault: true
    hasUrls: true
    template: pages/_router.html
    uriFormat: '{parent.uri}/{slug}'
structure:
  maxLevels: null
  uid: 0d289b9f-cb4d-4bcf-9064-25819bb1075d
type: structure
