field: d2bf91da-aaba-431f-8a30-62d58594b642 # Matrixfield
fieldLayouts:
  4c5ce5e0-eea5-4ca4-86c2-3f16563078f6:
    tabs:
      -
        elements:
          -
            fieldUid: 0b6f1179-0920-453b-8957-92eb6421cf54 # testfield
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  0b6f1179-0920-453b-8957-92eb6421cf54: # testfield
    columnSuffix: pkdwgrao
    contentColumnType: text
    fieldGroup: null
    handle: testfield
    instructions: ''
    name: testfield
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: testblock
name: testblock
sortOrder: 1
