contentColumnType: text
fieldGroup: 96f984ce-8346-4d4a-88c7-24800dbbf84d
handle: excerpt
instructions: ''
name: Excerpt
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: '1'
  placeholder: ''
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
