contentColumnType: string
fieldGroup: c9634d31-bea8-49e3-be82-09eb549cff97
handle: seoImage
instructions: ''
name: 'SEO Image'
searchable: true
settings:
  allowedKinds:
    - image
  defaultUploadLocationSource: 'volume:7754ddfc-22ac-4ed9-82f8-60c3310ad070'
  defaultUploadLocationSubpath: ''
  limit: '1'
  localizeRelations: false
  restrictFiles: '1'
  selectionLabel: ''
  singleUploadLocationSource: 'volume:7754ddfc-22ac-4ed9-82f8-60c3310ad070'
  singleUploadLocationSubpath: ''
  source: null
  sources: '*'
  targetSiteId: null
  useSingleFolder: '1'
  viewMode: large
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
