columnSuffix: aywjkpxz
contentColumnType: text
fieldGroup: 238b3570-fc81-4244-bf73-c9cdb18a2c1b # Common
handle: textfield
instructions: ''
name: Textfield
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
